"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# .env 파일 로드
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 환경 변수에서 값 가져오기
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'
DATA_GO_KR_API_KEY = os.getenv('DATA_GO_KR_API_KEY')

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage', #cloudinary(이미지 저장용)
    'django.contrib.staticfiles',
    'rest_framework', # DRF 추가
    'rest_framework_simplejwt', # JWT 인증을 위한 앱 추가
    'corsheaders', # CORS 추가
    'cloudinary', #cloudinary(이미지 저장용)
    'accounts', # 회원 정보 앱
    'weather', # 날씨 앱
    'board', # 게시판 앱
    'albums', # 앨범 앱
]

MIDDLEWARE = [
    # 1. 보안 관련 (가장 먼저 실행)
    'django.middleware.security.SecurityMiddleware',
    
    # 2. 정적 파일 서빙 (Whitenoise는 보안 미들웨어 바로 다음에)
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # 3. 세션 관리 (로그인 정보를 읽기)
    'django.contrib.sessions.middleware.SessionMiddleware',

    # 4. CORS 설정 (CommonMiddleware보다 위에 있어야 프론트엔드 요청을 가로채지 않음)
    'corsheaders.middleware.CorsMiddleware',

    # 5. 공통 처리 (URL 끝에 /를 붙여주는 등의 작업)
    'django.middleware.common.CommonMiddleware',

    # 6. CSRF 보안 (Post 요청 등을 검사)
    'django.middleware.csrf.CsrfViewMiddleware',

    # 7. 인증 (request.user를 사용할 수 있게 해줌)
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # 8. 메시지 프레임워크 (관리자 페이지 등에서 알림 띄울 때 사용)
    'django.contrib.messages.middleware.MessageMiddleware',

    # 9. 클릭재킹 방지
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'), # .env에서 읽어옴
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', #사용자 정보 유사도 검사
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', #최소 길이 검사
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', #흔한 비밀번호 검사
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', #숫자 전용 비밀번호 검사
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr' # 한국어로 설정

TIME_ZONE = 'Asia/Seoul' # 타임존을 서울(한국)로 변경

USE_I18N = True # 다국어 지원

USE_TZ = False # 데이터베이스에 저장할 때도 현지 시간을 사용할지 여부, False로 설정하면 Django가 TIME_ZONE에 설정된 시간을 그대로 사용합니다.


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 프로젝트 루트 폴더에 'staticfiles'라는 이름으로 정적 파일을 모으겠다는 설정(python manage.py collectstatic 명령어로 모을 때)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 정적 파일 설정 - Whitenoise를 사용하여 정적 파일을 효율적으로 서빙하기 위한 설정
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' #이전 버전에서는 이렇게 설정했지만, 최신 버전에서는 STORAGES 설정으로 대체
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# 도메인 허용 설정
# CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'False') == 'True'
# 쿠키 전송 허용 임시
#CORS_ALLOW_CREDENTIALS = True
# 특정 주소만 허용
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "https://luna-front-chi.vercel.app",
# ]
CORS_ALLOW_CREDENTIALS = False # 쿠키 전송 허용 여부 (False로 설정하면 쿠키 전송 안됨), Next.js의 리버스 프록시(rewrites) 기능 사용
CORS_ALLOW_ALL_ORIGINS = False # 모든 도메인 허용 여부 (False로 설정하면 CORS_ALLOWED_ORIGINS에 명시된 도메인만 허용)
CORS_ALLOWED_ORIGINS = [] # CORS 허용 도메인 리스트 (CORS_ALLOW_ALL_ORIGINS가 False일 때만 적용)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [ # 인증 설정 :  모든 API 엔드포인트에 대해 인증 없이 접근 허용
        'rest_framework.permissions.IsAuthenticated', # 기본적으로 로그인한 사람만 허용
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authenticate.CustomJWTAuthentication', # 쿠키에서 JWT를 읽어오는 커스텀 인증 클래스 추가
    ],
}

# 2. Simple JWT 상세 수명 및 보안 규칙 설정
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # 30분 뒤 자동 만료 (XSS 탈취 대비)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # 7일 동안 로그인 유지
    'ROTATE_REFRESH_TOKENS': True,                  # 리프레시 토큰 사용 시 새 토큰 발행 (보안 강화)
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),                # 이제 장고 스펙인 'Token' 대신 표준인 'Bearer'를 사용합니다!
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Cloudinary 설정
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Django 통합 저장소 설정
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# django-cloudinary-storage 호환성을 위해
STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticCloudinaryStorage'