# Generated by Django 6.0.1 on 2026-04-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JejuWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lng', models.FloatField(verbose_name='경도')),
                ('nx', models.IntegerField(verbose_name='기상청 NX')),
                ('ny', models.IntegerField(verbose_name='기상청 NY')),
            ],
            options={
                'verbose_name': '제주 지점 정보',
                'verbose_name_plural': '제주 지점 정보 목록',
            },
        ),
    ]
